erDiagram
    USERS ||--o{ GAME_SESSIONS : "user_id"
    USERS ||--o{ REVIEWS : "user_id"
    USERS ||--o{ REPORTS : "user_id"
    USERS ||--o{ UNLOCKED_ENDINGS : "user_id"
    
    GAME_SESSIONS ||--o{ SESSION_PATHS : "session_id"
    
    USERS {
        int id PK
        varchar pseudo UK "Unique"
        varchar email UK "Unique"
        varchar password "Hashed bcrypt"
        varchar role "lecteur|auteur|admin"
        boolean is_banned "Admin ban auteur"
        timestamp created_at
        timestamp updated_at
    }
    
    GAME_SESSIONS {
        int id PK
        int user_id FK "Ref users"
        varchar story_mongo_id "ObjectId MongoDB"
        varchar current_page_mongo_id "ObjectId MongoDB"
        varchar end_page_mongo_id "ObjectId MongoDB si termine"
        boolean is_completed "Partie finie"
        timestamp started_at
        timestamp completed_at
        timestamp updated_at "Derniere sauvegarde auto"
    }
    
    SESSION_PATHS {
        int id PK
        int session_id FK
        varchar page_mongo_id "ObjectId MongoDB visite"
        varchar choice_mongo_id "ObjectId MongoDB choix"
        int step_order "Ordre chronologique"
        timestamp created_at
    }
    
    REVIEWS {
        int id PK
        int user_id FK
        varchar story_mongo_id "ObjectId MongoDB"
        int rating "1 a 5 etoiles"
        text comment "Commentaire optionnel"
        timestamp created_at
        timestamp updated_at
    }
    
    REPORTS {
        int id PK
        int user_id FK "Qui signale"
        varchar story_mongo_id "ObjectId MongoDB signalee"
        text reason "Motif signalement"
        varchar status "pending|resolved|rejected"
        timestamp created_at
    }
    
    UNLOCKED_ENDINGS {
        int id PK
        int user_id FK
        varchar story_mongo_id "ObjectId MongoDB"
        varchar end_page_mongo_id "ObjectId MongoDB fin debloquee"
        timestamp unlocked_at
    }